import "./globals.css";
import { connectDb } from "@/config/mongo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectDb();
  return (
    <html lang="en">
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
